app = "b2d-ventures-backend"
primary_region = "sin"

# Remove the builder since we're using Dockerfile
# [build]
#   builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "mysite.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[statics]]
  guest_path = "/code/static"  # Updated to match Dockerfile WORKDIR
  url_prefix = "/static/"

[mounts]
  source = "b2d_ventures_data"
  destination = "/data"

[deploy]
  release_command = "python manage.py migrate"

# Update health check to use a path that exists in your Django app
[checks]
  [checks.health]
    port = 8000
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/"  # Change this to a path that exists in your app
    protocol = "http"

[metrics]
  port = 8000
  path = "/metrics"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024