app = 'b2d-ventures-backend'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  PYTHONUNBUFFERED = "1"
  DJANGO_SETTINGS_MODULE = "mysite.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "30s"
    interval = "45s"
    method = "GET"
    path = "/health/"
    protocol = "http"
    timeout = "10s"
    restart_limit = 3
    [http_service.checks.headers]
      Host = "localhost"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  swap_size_mb = 512

[services]
  [[services.ports]]
    handlers = ["http"]
    port = 8000
    force_https = true

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'