# Generated by Django 4.2.15 on 2024-11-10 02:22

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="refresh_token",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
