# Generated by Django 4.2.15 on 2024-08-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("image_url", models.URLField(max_length=255)),
                ("allocation", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "minimum_investment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "raised",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("investor_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="app.startup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income_statement", models.TextField(blank=True)),
                ("balance_sheet", models.TextField(blank=True)),
                ("cash_flow_statement", models.TextField(blank=True)),
                (
                    "revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "ebitda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "burn_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("runway", models.IntegerField(blank=True, null=True)),
                (
                    "current_valuation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("valuation_method", models.CharField(blank=True, max_length=100)),
                ("previous_funding_rounds", models.TextField(blank=True)),
                (
                    "total_funding_raised",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("revenue_projections", models.TextField(blank=True)),
                ("profit_projections", models.TextField(blank=True)),
                (
                    "market_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "market_growth_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("business_model", models.TextField(blank=True)),
                ("revenue_streams", models.TextField(blank=True)),
                (
                    "user_acquisition_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "customer_lifetime_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "churn_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("patents", models.TextField(blank=True)),
                ("trademarks", models.TextField(blank=True)),
                ("key_team_members", models.TextField(blank=True)),
                ("advisors", models.TextField(blank=True)),
                ("legal_structure", models.CharField(blank=True, max_length=100)),
                ("regulatory_compliance", models.TextField(blank=True)),
                (
                    "pitch_deck",
                    models.FileField(blank=True, null=True, upload_to="pitch_decks/"),
                ),
                (
                    "business_plan",
                    models.FileField(
                        blank=True, null=True, upload_to="business_plans/"
                    ),
                ),
                (
                    "financial_model",
                    models.FileField(
                        blank=True, null=True, upload_to="financial_models/"
                    ),
                ),
                ("access_permissions", models.TextField(blank=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("update_history", models.TextField(blank=True)),
                (
                    "startup",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_room",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealInvestor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("investment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_investors",
                        to="app.deal",
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("deal", "investor")},
            },
        ),
    ]
