# Generated by Django 4.2.15 on 2024-11-10 03:23

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_refresh_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="refresh_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, default="", null=True
            ),
        ),
    ]
