# Generated by Django 4.2.15 on 2024-08-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="type",
            new_name="role",
        ),
    ]
