# Generated by Django 4.2.15 on 2024-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_raised_deal_amount_raised_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("investor", "Investor"),
                    ("startup", "Startup"),
                    ("unassigned", "Unassigned"),
                    ("pending_investor", "PendingInvestor"),
                    ("pending_startup", "PendingStartup"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
    ]
