# Generated by Django 4.2.15 on 2024-08-31 07:41

import b2d_ventures.app.models.deal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_deal_dataroom_delete_dataroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="image_background_url",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="image_content_url",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="image_logo_url",
        ),
        migrations.AddField(
            model_name="deal",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="deal",
            name="image_background",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="image_content",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="image_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png"]
                    )
                ],
            ),
        ),
    ]
