# Generated by Django 4.2.15 on 2024-08-31 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_deal_image_background_url_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="investor",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="meetingparticipant",
            name="startup",
        ),
        migrations.RenameField(
            model_name="investment",
            old_name="amount",
            new_name="investment_amount",
        ),
        migrations.RenameField(
            model_name="investment",
            old_name="date",
            new_name="investment_date",
        ),
        migrations.AddField(
            model_name="meeting",
            name="investor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.investor",
            ),
        ),
        migrations.AddField(
            model_name="meeting",
            name="startup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.startup",
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_investors",
                to="app.deal",
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal_investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="DealInvestor",
        ),
        migrations.DeleteModel(
            name="MeetingParticipant",
        ),
    ]
