# Generated by Django 4.2.15 on 2024-09-03 02:44

import b2d_ventures.app.models.deal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_meetingparticipant_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="image_background",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="image_content",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="image_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
            ),
        ),
    ]
