# Generated by Django 4.2.15 on 2024-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_meeting_options_remove_meeting_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.CharField(default="", max_length=150, null=True),
        ),
    ]
