# Generated by Django 4.2.15 on 2024-11-04 13:39

import b2d_ventures.app.models.deal
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_deal_dataroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="image_background",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="image_content",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="image_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to=b2d_ventures.app.models.deal.deal_image_upload_path,
            ),
        ),
    ]
